#!/bin/sh

ENV=dw
LDAP_SERVER="ldap://lbdc-use1.sea.corp.expecn.com:389"
CSV="pmi-${ENV}.csv"
[ -f $CSV ] && rm $CSV
SAPW=`cat s-workflow-orchestra.cred`
APIHOST=https://wo-api.wo-eks-us-east-1.data.${ENV}.exp-aws.net
echo "Generating SG list from $APIHOST"
if [ $# -gt 0 ]; then
  CLIENTS=$*
else
  jsonlist=`curl -s -X GET --header 'Accept: application/json' $APIHOST/api/v3/airflow/clients?force_refresh_cache=false`
  CLIENTS=`echo $jsonlist | jq -r '.[]' | tr '\n' ' '`
fi
echo CLIENTS: $CLIENTS
SGC=0
for c in $CLIENTS; do
   CLIENT=$c
   printf "%s..." "${CLIENT}"
   USERS=0
   SG=`curl -s -X GET --header 'Accept: application/json' $APIHOST/api/v3/airflow/clients/${CLIENT} | jq -r '. | .admin_security_group_name'`
   usernames=`ldapsearch -x -H $LDAP_SERVER -D "SEA\\s-workflow-orchestra" -w $SAPW -b 'DC=SEA,DC=CORP,DC=EXPECN,DC=com' "(memberOf=CN=${SG},OU=Security Groups,DC=SEA,DC=CORP,DC=EXPECN,DC=com)" mail | grep -v 's-' | grep "mail:" | cut -d " " -f 2 | awk -F\@ '{print "member,user," $1 "," $1 "@expediagroup.com," $1 "\n"}'`
   for u in $usernames; do
      echo $u >>$CSV
      let USERS=USERS+1
   done
   echo $USERS users
   let SGC=SGC+1
done
echo $SGC SGs

TEMP=$(mktemp)
cat $CSV | sort | uniq >$TEMP
mv $TEMP $CSV

echo `cat $CSV | wc -l` unique users.
